{% set version = "0.3.6" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-factormerger
  version: {{ version|replace("-", "_") }}

source:
  fn: factorMerger_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/factorMerger_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/factorMerger/factorMerger_{{ version }}.tar.gz
  sha256: 807a9269f5b2c2216b3b5d70f6eb8656cd27cf8862af4e26e615464705178512

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-mass
    - r-agricolae
    - r-colorramps
    - r-dplyr
    - r-forcats
    - r-formula.tools
    - r-ggplot2
    - r-ggpubr
    - r-knitr
    - r-magrittr
    - r-mvtnorm
    - r-proxy
    - r-reshape2
    - r-scales
    - r-survival

  run:
    - r-base
    - r-mass
    - r-agricolae
    - r-colorramps
    - r-dplyr
    - r-forcats
    - r-formula.tools
    - r-ggplot2
    - r-ggpubr
    - r-knitr
    - r-magrittr
    - r-mvtnorm
    - r-proxy
    - r-reshape2
    - r-scales
    - r-survival

test:
  commands:
    - $R -e "library('factorMerger')"  # [not win]
    - "\"%R%\" -e \"library('factorMerger')\""  # [win]

about:
  home: https://github.com/MI2DataLab/factorMerger
  license: GPL
  summary: The Merging Path Plot is a methodology for adaptive fusing of k-groups  with likelihood-based
    model selection. This package contains tools for  exploration and visualization
    of k-group dissimilarities.  Comparison of k-groups is one of the most important
    issues in exploratory analyses and it has zillions of applications.  The traditional
    approach is to use pairwise post hoc tests in order to verify which groups differ
    significantly. However, this approach fails with a large number of groups in both
    interpretation  and visualization layer. The Merging Path Plot solves this problem
    by using an easy-to-understand  description of dissimilarity among groups based
    on Likelihood Ratio Test (LRT) statistic. Work on this package was financially supported
    by the 'NCN Opus grant 2016/21/B/ST6/02176'.
  license_family: GPL

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
