travis:
  secure:
    BINSTAR_TOKEN: Qy+O3BeWmLn3Akuu33trL0pn6IgYryPYPWPnPVNKtT9c0m1nbzoiUVSnoZW1ohOeUOpM+8uNhAHnsvKUOJMNrguPEuu3UPRMeTEgCu8yP0AHMcUf7GVGAadQLYTJLCmGbSLiwl56DukzGzKHXMUDYSJWV4FVTtwnck8H8XRD7ZuPOWi7Aby2MRSNRxsWqug6vwdwVpu5hRPHG0L0IEUgcm8HFZWnLJfAA5lp6bDbjSNBee4+GxLC8k6QaQitS5z3sH+cJoyDPIqHZHdc8WXY3ZKKhf8XmKMte4AXQXU1xHGCYQiJtjvZ8CTteYvDeSl2f/k/jju/6Ur5tBIh18JAFdcByQbUwzz7z36VgZ+Peah0GVizQ0VgsU8GojOsDUpIcgQZMejwKIYkHuFH0E4F/yyh9uaTJgPBmydeqs+R0yCkqoufxJ6SKR55vB+kZQLA/ftiqO9HNs46ZWb6wib3GJ6jlerYmjxHtHe7nDnwNsi9l4nPlFNT59HBNVqt20TsbedHVmb0TW4HcMT5XsRF10yPZ+8bstOJxJlD+ax7UDSXrieUiHlQsH+kQG72WpDIt+6ebCzNvV3p9Fr/uRrfzMcULZ2bjk241wzeoqFYFpANQjlLm9974Gr7ylYiO5YbTQOup/ymvRsDvGoM8CuTirUJOs8WaWop6nlveM0M6GY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
