travis:
  secure:
    BINSTAR_TOKEN: nvsG54pmXvC441ahTU+FX5T2VRDkQ4GG72ksu9qXh7yvNb7BC+yXuA9R4vFO4LDlYHDrnR7dxnwX8ov11cBx/hCvwBm5e202FKtdnSBev7gKrHzL4BYIK+gJYTx5s9Z6Zyxetyo9KzzT8VMEFfUk8k750q01vokPLiKxxv0si0bxT/D5Dvp5sxqEXZ6kzGVppabTZlxnNRSq1ED3oyVBGSDJhp5Papa+VaslJ/R1qMRoS3VplSJRKdKa2whITebr8fAM7z1gH+1vvuse95zdbys8HNk8DNBzwEt72sW4LaIciCdkk2LkLFHK/QOk0aNBtdrxfLKkurrxySe9fDveTmMl4vikJ4F2NS6OeBECT8x+aT755jixY8epMbkrruVKD+lyvsQ85kC+hgDC7+DXn5DO4CB3nE+r3oIn9enYQNUU9bE+2NcxGJCwFAXT1C4Rmy1SoSuqGLfwxsLOL3Wlc+qktnEAuJNEECcxjLDFMuRhcaZx2nZH553pm7rxMiZtoXzJruybDNdyarK+K2VFbJR7h+JU+lGHIthaHBdeHvgN2EOREoanmGsJTRuA9Qp69OhdtWG3Y7ua5NnbHflHe8NjSo1+71qyFxOgU+Ji/H76Mpy3cK5njCiVQtdUAOKyCV29m+209hgZrYQDS22FLGA1ANI844VLMa/eKLIVsGk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
