travis:
  secure:
    BINSTAR_TOKEN: pnyJjj7leiop7U2HMmKPIPcTVkgqdnDKO8BSNUz2LUBJ9uVIY9AyNJ799gSYzFZtgSsKM7+mCl5+jB6UTaTlsGRMNbby+f9bZz3/ncEsYezHDZsS94QP4GpvkyNme+I8ylGBPiFs/3ghal88b66kxU69tfka3WDGKFVvlBkvHn2gKdmM5YILoSGlYcl60kVarW4LbEn5itWYrn04N3A9qjGRkr24TnhOJui2/tmykc6/CEFbf2cGEuvVxe1zb3Mpu5dYFDOYemU8/Y3A2e0uesRMz/5lJ06olCy2bMRKJp3082kG5ZY0+hkbf6gNVLze85FUAly6ws6h/DO/ygI4BLGx22J2k/rGcslhMZJWYNdnItpFxlj9/3xkOyr9e0dpuoflxNzg6lb+wy0s+n3iWxuL7+OxwgzX/KUUSySwLWbTU1sd6bbXhw928pigzGGYWaH8HltwW6ROeSBUI2dm6lGsRMpyUo27Z4zFGeSbue3kO6L31N+Rmv2M5+WtAXFJ2fEPxRiXcNcWxLPWiW1lWQvSRJIBIKofAEcQUtfWiVBsE7Y1IltT6hophET8r9mwvOkb5FXqEAez+WGhdMWXv1ex+lYISkKINOKQe53DcZBoc0D2t4lLGMHBmpZktws/b3VLH1rbn3DDmKQlugDs6c4DXnvkoP8VfC4Ja8sUHbw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
